### ISSUE TITLE
support for node 0.10 ?

### ISSUE THREAD

**Issue by guymguym** [vmolsa/webrtc-native#1]
nice! I like the native approach :+1: 
build.js fails immediately with node 0.10 due to execSync missing from child_process, which is an easy thing to fix.
though I wonder if the rest of the native code supports node 0.10 ?

**Comment by vmolsa** [comment]
No this version of node webrtc is only working with latest nodejs. v0.12.x

**Comment by vmolsa** [comment]
Just need to rewrite 5000 lines of code with using nan.

**Comment by vmolsa** [comment]
Now supports older versions and Iojs.
