### ISSUE TITLE
Simple-peer tests fail

### ISSUE THREAD

**Issue by Chocobozzz** [vmolsa/webrtc-native#23]
Hi,

Tests in the [simple-peer](https://github.com/feross/simple-peer/tree/master/test) package fail:
- the **basic.js** fails because GetStats seems to return an array of empty hashes
- the **trickle.js** fails because the simple-peer doesn't receive an `onicecandidate` with a null candidate (see https://github.com/js-platform/node-webrtc/pull/123).

I wanted to test webrtc-native for the webtorrent-hybrid project, but it doesn't work because of these bugs I guess.

I tried to compile the module myself in order to make some tests, but it doesn't seem to work with the latest chromium code. Can you share the version you use?

Thanks for your work,
Chocobozzz

**Comment by vmolsa** [comment]
Hi, webrtc-native tests are written with simple-peer and tests go through on all platforms (ubuntu 14.04, windows 8.1, OSX)

```sh
npm test
```

I'm using chromium 47. On linux there is a bug in chromium when app is closing and that is causing sigsegv.

Building webrtc-native with chromium 47.

```sh
git clone https://github.com/vmolsa/webrtc-native
cd webrtc-native
git checkout stable
cd third_party/webrtc/src/
git checkout branch-heads/47
cd ../../../
export BUILD_WEBRTC=true
npm install
npm test
```

But I check those problems.. Thanks! :)

**Comment by Chocobozzz** [comment]
Thanks for your response, I'll retry the build :)

But I talked about the tests **of** the simple-peer module by replacing at the line 4: `wrtc` with `webrtc-native` (https://github.com/feross/simple-peer/blob/master/test/trickle.js for example). I'll try to check this me too. 

Thanks to check it, I'll try to make the same :)

**Comment by vmolsa** [comment]
Yes i know that you meant the simple-peer tests but when webrtc-native tests are written with same lib then why they don't work?.. It's same lib anyway..

**Comment by Chocobozzz** [comment]
Oh sorry, and yes I've seen that this is strange. 

But tests pass if we remove the part about the stats (https://github.com/feross/simple-peer/blob/master/test/basic.js#L62) and if the **trickle** is set to true (which is the default). The *trickle.js* file test simple-peer with the option set to false (https://github.com/feross/simple-peer/blob/master/test/trickle.js#L16). 

So if in the tests of `webrtc-native` the option **trickle** is not explicitely set to false, this could be the explication why the tests pass.

**Comment by vmolsa** [comment]
It's seems that chromium sync is broken now :/ again.. But you are right there is no null candidate so I'm adding it to stable branch.

**Comment by vmolsa** [comment]
This issue is quite old and there's many changes done after this so i'm closing this one..
