### ISSUE TITLE
Prebuilt modules for windows

### ISSUE THREAD

**Issue by alaa-eddine** [vmolsa/webrtc-native#28]
Hi, 

I'm interested in this library to add crossplatform webrtc support to [eureca.io](https://github.com/Ezelia/eureca.io) 
right now I'm using [node-webrtc](https://github.com/js-platform/node-webrtc), but it only support linux.

I have two questions
 - I don't have a windows environment with the prerequisties to build the module, are there any prebuilt binaries ? 
 - since node-webrtc implements the WebRTC API as webrtc-native does, can I expect that the code using node-webrtc will remain compatible with webrtc-native or there are gotchas :) ?

**Comment by alaa-eddine** [comment]
I managed to get a windows environment with prerequisties and tried to build .
After about two hours (gsync + build) I get this error 

**fatal error C1083: Cannot open include file: 'usrsctplib/usrsctp.h': No such file or directory**


Any idea ?

--------------
--------------


I attached below the last lines before error + the full error message

```
[1709/1957] CXX obj\talk\media\sctp\libjingle_media.sctpdataengine.obj

[1710/1957] CXX obj\talk\media\devices\libjingle_media.filevideocapturer.obj

FAILED: ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\talk\media\sctp\libjingle_media.sctpdataengine.obj.rsp /c ..\..\talk\media\sctp\sctpd
  ataengine.cc /Foobj\talk\media\sctp\libjingle_media.sctpdataengine.obj /Fdobj\talk\libjingle_media.cc.pdb

c:\ezelia\webrtc-native\third_party\webrtc\src\talk\media\sctp\sctpdataengine.cc(38): fatal error C1083: Cannot open include file: 'usrsctplib/usrsctp.h': No such file or directory [C:\ezelia\webrtc-native\build\action_before_build.vcxp
roj]

  ninja: build stopped: subcommand failed.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\ezelia\webrtc-native\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\ezelia\\webrtc-native\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\ezelia\webrtc-native
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
```

**Comment by alaa-eddine** [comment]
After some headache I think I managed to compile it :)

first of all  sctpdataengine.cc will look for missing usrsctplib/usrsctp.h 

This one was easy, I just cloned usrsctplib in third_party\webrtc\src\talk\media\sctp\ folder

```
git clone https://chromium.googlesource.com/external/usrsctplib
```

Then I got another error about a missing/unknown identifier TLS1_CK_ECDHE_ECDSA_CHACHA20_POLY1305 this one was tricky .... 
after some digging I found that a recent patch was made to "boringssl" (here https://boringssl.googlesource.com/boringssl/+/fb974e6cb314735e06771887ef8fdcbe837851ee%5E!/) 

and in this patch TLS1_CK_ECDHE_ECDSA_CHACHA20_POLY1305 was replaced by **TLS1_CK_ECDHE_ECDSA_CHACHA20_POLY1305_OLD**

there was also some other changes but since the compiler was only complaining about TLS1_CK_ECDHE_ECDSA_CHACHA20_POLY1305 I replaced it with TLS1_CK_ECDHE_ECDSA_CHACHA20_POLY1305_OLD and .... it did it :)


the module is now built, and when I run node test/all.js I get all tests OK : 25/25 .... so I assume the it's a success :)

next step, I'll try to implement it in eureca.io

**Comment by alaa-eddine** [comment]
I'm closing this issue, after some tests the module is working just fine :)

**Comment by LeifRoss** [comment]
Hi,
Good job, I myself can't get this module to build without errors, built webrtc for c++ a few days ago, but not sure how to properly proceed with node.

I would be very grateful if you shared the built version! :)

My system is x64 windows 10, node v4.3.1.

**Comment by alaa-eddine** [comment]
here is the prebuilt version : http://labs.ezelia.com/webrtc-native/webrtc.node 
you just need to put it under build/release/ folder.

let me know if it work for you

**Comment by LeifRoss** [comment]
Thank you so much, it works like a charm!

**Comment by vmolsa** [comment]
Hi, There is so many changes in googles WebRTC project that code is changing all the time and for now there hasn't been any "stable" release that could be build on all platforms without any errors.. But soon i will update webrtc-native to latest WebRTC..

**Comment by LeifRoss** [comment]
Ah, I understand. You are doing a damn fine job with this library btw! It should be a part of the node base.
