### ISSUE TITLE
npm install hangs when downloading module (osx)

### ISSUE THREAD

**Issue by Figedi** [vmolsa/webrtc-native#31]
Very Strange issue:

I used this library successfully for the past months (1.2.2) and decided to update to the latest changes. I always prefer a clean install for all node modules, so i did a fresh install. My setup is as follows:
* node 0.12.12 (cant really change that coz of other deps)
* npm 3.6.0
* OSX 10.11.3

I'm using nvm for node versioning. When running `npm install` it downloads the binary like always, but it gets stuck at `Done! :)`, thus also preventing install of other modules. 

I also did a fresh clone of the project and tried to install it there, but same output. Loglevel silly doesn't output anything useful (Downloading module..., Loading module..., Done :))

When compiling from scratch it works, however given my project should run in various environments, this shouldn't really be an option.

Any tips how to resolve this?

**Comment by vmolsa** [comment]
Fixed.
