### ISSUE TITLE
Prebuilt binaries not versioned

### ISSUE THREAD

**Issue by Figedi** [vmolsa/webrtc-native#32]
Somehow related to my findings in #31. 

When downloading a module, it is not versioned by the lib itself, i.e. I use an older Version of webrtc-native (1.2.2 vs current 1.3.4), it is downloading the module as of 
```
URL += 'webrtc-' + PLATFORM + '-' + ARCH + '-' + NODEVER + '.node';
```
and eventually returning (although it hangs up first due to #31 on my machine). However after using the module, it is clearly not the desired version (url is not versioned + the downloaded binary has the new chromium 50 api changes, e.g. new RTCStats format).

My proposal would be to keep the binaries of previous versions by downloading a versioned binary, then during piping of the request just rename it to webrtc.node as usual

**Comment by vmolsa** [comment]
After switching to branch chromium 50. webrtc-native can now be builded on all platforms without any errors and i added the module version prefix.
