### ISSUE TITLE
what is the state of 2.x version?

### ISSUE THREAD

**Issue by notedit** [vmolsa/webrtc-native#43]

**Comment by vmolsa** [comment]
there are library issues when using libcrtc and node and that is causing SIGSEGV on Linux platform.
And after running tests when using chromium it is quite "expensive", Meaning that memory and CPU heavy for even simple tasks.  I may be moving this project into deprecated.

**Comment by notedit** [comment]
that is  sad

**Comment by getkey** [comment]
What are your thoughts on the (seemingly dead) related project [js-platform/node-webrtc](https://github.com/js-platform/node-webrtc)?
Why are these separated projects if both try to achieve the same thing? Is there a fundamental difference on how they are implemented?

**Comment by wildekek** [comment]
Hi @vmolsa, would using the these precompiled binaries fix the issue? https://sourcey.com/precompiled-webrtc-libraries/
Their build scripts for webrtc seem pretty solid.
