### ISSUE TITLE
simple-peer fails on undefined pc.remoteDescription

### ISSUE THREAD

**Issue by guymguym** [vmolsa/webrtc-native#7]
```
$ node test/bwtest.js 
bwtest args: { _: [] }
~/code/webrtc-native/node_modules/simple-peer/index.js:151
      if (self._pc.remoteDescription.type === 'offer') self._createAnswer()
                                    ^
TypeError: Cannot read property 'type' of undefined
    at RTCPeerConnection.<anonymous> (~/code/webrtc-native/node_modules/simple-peer/index.js:151:37)
```

**Comment by vmolsa** [comment]
SCTP / RTP dataChannels are now working with webrtc branch 43. 
But npm test still fails
 
to checkout webrtc to 43 branch run commands in third_party/webrtc/src folder
```
git checkout remotes/branch-heads/43
git reset --hard 5027d1c
````
and after that just rebuild it.

````
node-gyp rebuild
````

**Comment by guymguym** [comment]
wouldn't it be better off to checkout branch 43 by default then?

**Comment by vmolsa** [comment]
Fixed. But there is missing callback for send prototype in simple-peer. And that's why bwtest.js is failing..

**Comment by guymguym** [comment]
fixed in PR #8

**Comment by vmolsa** [comment]
On windows multiconnect test hangs after successful test and bwtest sometimes just fails.. 

SENDING: sent 0 received 0. congestion #0 0.000 seconds. took 0.004 seconds. bandwidth 0 KB/s.
SENDING: sent 100 received 74. congestion #304 1.705 seconds. bufferedAmount 196608. took 1.782 seconds. bandwidth 664 KB/s.
SENDING: sent 200 received 140. congestion #312 1.747 seconds. bufferedAmount 786432. took 1.837 seconds. bandwidth 1219 KB/s.
SENDING: sent 300 received 260. congestion #583 3.272 seconds. bufferedAmount 573440. took 3.407 seconds. bandwidth 1221 KB/s
sending: sent 300 received 260. congestion #583 3.272 seconds. bufferedAmount 573440. took 3.407 seconds. bandwidth 1221 KB/s.
npm ERR! Test failed.  See above for more details.

**Comment by vmolsa** [comment]
npm test still hangs on windows but i'm closing this one.
