### ISSUE TITLE
build takes too much time

### ISSUE THREAD

**Issue by guymguym** [vmolsa/webrtc-native#9]
took nearly 1 hour on macbook air.
this is too much friction for any user.

**Comment by guymguym** [comment]
add to that the fact that it ends up taking 6.5GB of disk space...

**Comment by vmolsa** [comment]
Prebuilt binaries is needed indeed but where to host them? node-pre-gyp / travis  / appveyor / amazon s3?

**Comment by piranna** [comment]
> node-pre-gyp / travis / appveyor / amazon s3?

Seems to be the way.

**Comment by vmolsa** [comment]
webrtc-native build takes too much time for travis but prebuilt modules are now working?. 
By default npm install fails if prebuilt module not found. but setting env BUILD_WEBRTC=true and rerun "npm install" to start to build from source.

**Comment by piranna** [comment]
If you are already building it with Travis you could publish them somewhere node-pre-gyp can fetch them. I'm doing so for each successful build of NodeOS, publishing them as pre-releases on GitHub.
